config/routes.rb
Rails.application.routes.draw do
  resources :join_table_items_carts, only: [:create, :update, :destroy]
  resources :carts, except: [:index, :new, :edit]
  devise_for :users
  root to: "items#index"
  resources :items

  #route du système de paiement stripe
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    end

end



  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :join_table_items_carts, dependent: :nullify
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :orders
    has_many :users, through: :orders
    has_many :join_table_items_carts, dependent: :nullify
end

app/models/join_table_items_cart.rb
class JoinTableItemsCart < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  def self.add_or_create_cart_item_link(permit_link_params)
    if JoinTableItemsCart.find_by(cart_id: permit_link_params[:cart_id], item_id: permit_link_params[:item_id]) == nil
      @new_item_add = JoinTableItemsCart.create(item_id: permit_link_params[:item_id], cart_id: permit_link_params[:cart_id], quantity: 1)
    else
      @new_item_add = JoinTableItemsCart.find_by(cart_id: permit_link_params[:cart_id], item_id: permit_link_params[:item_id])
      @new_item_add.update(quantity: @new_item_add.quantity + 1)
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord

    
    belongs_to :item
    belongs_to :user
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  #Callbacks
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now 
  end

    has_many :orders
    has_many :items, through: :orders
    has_many :items
    has_one :cart

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  after_action :create_cart_and_assign_to_current_user, only: [:create] 
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CartHelper

  before_action :require_login
  before_action :only_current_user_cart

  def show
    @items = Item.all
    @items_in_cart = JoinTableItemsCart.where(cart_id: current_user.cart.id)
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    def new
    @cart = Cart.find(params[:cart_id])
    end
    def create
    @user = current_user
    @total = params[:total].to_d
    @session = Stripe::Checkout::Session.create(
    payment_method_types: ['card'],
    line_items: [
    {
    name: 'Rails Stripe Checkout',
    amount: (@total*100).to_i,
    currency: 'eur',
    quantity: 1
    },
    ],
    success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
    cancel_url: checkout_cancel_url
    )
    respond_to do |format|
    format.js
    end
    end
    def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    end
    def cancel
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    end
    

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ItemsHelper

  before_action :save_items_in_cart

  def index
    @items = Item.all
    @join_table_items_cart = JoinTableItemsCart.new
  end

  def show
    @item = Item.find(params[:id])
    @join_table_items_cart = JoinTableItemsCart.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to item_path(@item.id)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price)
  end
end

app/controllers/join_table_items_carts_controller.rb
class JoinTableItemsCartsController < ApplicationController
  def create
    @item_add = JoinTableItemsCart.add_or_create_cart_item_link(permit_link_params)
    redirect_to items_path
  end

  def update
  end

  def destroy
    @item_delete = JoinTableItemsCart.find(params[:id])
    @item_delete.destroy
    redirect_to cart_path
  end

  private

  def permit_link_params
    params.require(:join_table_items_cart).permit(:item_id, :cart_id, :quantity)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = User.find(current_user.id)
    end
    
    def edit
        @user = User.find(current_user.id)
       end
       
       def update
           @user = User.find(current_user.id) 
       
         
           if @user.update(user_params)
             redirect_to @user
           else
             render :edit
           end
       end
       
       private
       
       def user_params
           user_params = params.require(:user).permit(:first_name,:last_name, :adress, :zipcode)
       end    

end

app/helpers/application_helper.rb
module ApplicationHelper
  def create_cart_and_assign_to_current_user
    if current_user != nil && current_user.cart == nil
    cart = Cart.create(user: current_user)
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
  private

  def require_login
    unless current_user != nil
      redirect_to new_user_session_path
    end
  end

  def only_current_user_cart
    if current_user != nil && current_user.cart.id != params[:id].to_i
      return redirect_to cart_path(current_user.cart.id)
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def save_items_in_cart
    if current_user != nil
      @items_in_cart = JoinTableItemsCart.where(cart_id: current_user.cart.id)
    end
  end
end

app/helpers/join_table_items_carts_helper.rb
module JoinTableItemsCartsHelper
end

app/views/carts/create.html.erb
<h1>Cart#create</h1>
<p>Find me in app/views/cart/create.html.erb</p>

app/views/carts/destroy.html.erb
<h1>Cart#destroy</h1>
<p>Find me in app/views/cart/destroy.html.erb</p>

app/views/carts/show.html.erb
<br/>
<div class="container">
  <h1>Mon panier</h1>
  <br/>
  <br/>
  <div class="row">
    <div class="col-lg-8 col-md-8">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Quantité</th>
            <th scope="col">Nom de produit</th>
            <th scope="col">Prix unitaire</th>
            <th scope="col">Prix selon quantité</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% total_price = [] %>
          <% @items_in_cart.each do |item| %>
          <tr>
            <th scope="row"><%= item.quantity %></th>
            <td><%= item.item.name %></td>
            <td><%= item.item.price %>€</td>
            <td><%= total_item = item.item.price * item.quantity.to_d %>€</td>
            <% total_price << total_item %>
          </tr>
          <% end %>
          <tr>
            <th scope="row"></th>
            <td><a href="<%= join_table_items_cart_path(item.id) %>" class="btn btn-danger" data-confirm="Etes-vous sûr de vouloir supprimer cet article du panier?" data-method="DELETE">Supprimer l'article</a></td>
            <td></td></td>
            <td></td>
          </tr>
          <tr>
            <th scope="row"></th>
            <td></td>
            <td class="font-weight-bold">Prix total :</td>
            <td><%= total_price.inject(0) { |sum, x| sum + x } %>€</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/carts/update.html.erb
<h1>Cart#update</h1>
<p>Find me in app/views/cart/update.html.erb</p>

app/views/checkout/ success.html.erb
<div class="container text-center my-5">
<h1>Succès</h1>
<p>Super le paiement réussi<p>
<p>Le statut du paiement est : <%= @payment_intent.status %> </p>
</div>

app/views/checkout/cancel.html.erb
<div class="container text-center my-5">
<h1>Cancel</h1>
<p>Dommage t'es pauvre, retourne chez maman!!<p>
<p>Le statut du paiement est : <%= @payment_intent.status %> </p>
</div>

<%= button_to "Passer commande", checkout_create_path(total: @cart.price), class: "btn btn-outline-primary my-3", remote: true %>

app/views/checkout/create.js.erb
var stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');
var stripe = Stripe('la_cle_publique_ici');
stripe.redirectToCheckout({
sessionId: '<%= @session.id %>'
}).then(function(result){
console.log(result.error.message);
console.log(result.errors.messages);
});

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<div class="container">
  <br/>
  <h1>Modifier l'article </h1><br/>
  <br/>
  <%= form_for @item do |f| %>
  <div class="form-group">
    <label class="form-label">Nom de l'article</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="form-label">Description de l'article</label>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="form-label">Prix de l'article</label>
    <%= f.number_field :price, step: 0.01, class: 'form-control' %>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-success">Modifier l'article</button>
  </div>
  <br/>
  <a href="<%= items_path %>" class="btn btn-secondary">Retourner à l'accueil</a>
  <a href="<%= item_path(@item.id) %>" class="btn btn-secondary">Retourner sur l'article</a>
  <% end %>
</div>

app/views/items/index.html.erb
<br><br>
<div class="container">
  <h1>Tout les articles</h1><hr><br/><br/>
    <div class="row justify-content-center">
      <% @items.each do |item| %>
        <div class="col-12 col-lg-3 col-md-6 mb-3">
          <div class="card m-3 card-home" style="width: 18rem;">
             <div class="card-image">
              <%# <%=image_tag (item.image_url)%>
            </div>
            <div class="card-body">
              <h5 class="card-title">Nom : <%= item.name %></h5>
              <p class="card-text">Description : <%= item.description %></p>
              <p style="overflow-y:scroll;height:25px" class="card-text">Valeur : <%= item.price %>€</p>
              <a href="<%= item_path(item.id)%>" class='btn btn-primary'>En Savoir plus</a>
            </div>
            <% if user_signed_in? %>
              <%= form_for @join_table_items_cart do |f| %>
              <%= f.hidden_field :item_id, value: item.id %>
              <%= f.hidden_field :cart_id, value: current_user.cart.id %>
               <button type="submit" class='btn btn-success'>Ajouter au panier</button>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/items/new.html.erb
<div class="container">
<br/>
<h1>Creer un nouvel article </h1>
<br/>
<br/>
<%= form_for @item do |f| %>
<div class="form-group">
<label class="form-label">Nom de l'article</label>
<%= f.text_field :name, class: 'form-control' %>
</div>
<div class="form-group">
<label class="form-label">Description de l'article</label>
<%= f.text_area :description, class: 'form-control' %>
</div>
<div class="form-group">
<label class="form-label">Prix de l'article</label>
<%= f.number_field :price, step: 0.01, class: 'form-control' %>
</div>
<div class="form-group">
<button type="submit" class="btn btn-primary">Créer l'article</button>
</div>
<% end %>
</div>

app/views/items/show.html.erb
<br/><br/><br/>
<div class="container">
  <h1><%= @item.name %></h1>

  <br/>
  <h4>Description de l'article:</h4>
  <p><%= @item.description %></p>
  <br/>
  <p>Prix: <%= @item.price %>€</p>
  <%= form_for @join_table_items_cart do |f| %>
    <%= f.hidden_field :item_id, value: @item.id %>
    <%= f.hidden_field :cart_id, value: current_user.cart.id %>
    <button type="submit" class="btn btn-success">Ajouter au panier</button>
  <% end %>
  <br/><br/>
  <a href="<%= edit_item_path %>" class="btn btn-warning">Modifier</a>
  <a href="<%= item_path(@item.id) %>" class="btn btn-danger" data-confirm="Êtes-vous sûr de vouloir supprimer cet article ?" data-method="DELETE">Supprimer</a>
  <br/>
  <br/>
  <a href="<%= root_path %>" class="btn btn-secondary">Retourner à l'accueil</a>
</div>
<br/><br/><br/>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/join_table_items_carts/create.html.erb
<h1>JoinTableItemsCarts#create</h1>
<p>Find me in app/views/join_table_items_carts/create.html.erb</p>

app/views/join_table_items_carts/destroy.html.erb
<h1>JoinTableItemsCarts#destroy</h1>
<p>Find me in app/views/join_table_items_carts/destroy.html.erb</p>

app/views/join_table_items_carts/update.html.erb
<h1>JoinTableItemsCarts#update</h1>
<p>Find me in app/views/join_table_items_carts/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= favicon_link_tag 'favicon.png' %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
  <%= render partial: "shared/banner" %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render partial: "shared/footer" %>
  </body>
  <script src="https://js.stripe.com/v3/"></script>

</html>

app/views/shared/_banner.html.erb
 <div class="banner">
  <section class="py-5 text-left container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">La plus grande <br>sélection en Europe</h1>
        <p class="lead">Découvrez plus de 2000 photos et profitez <br> d’une livraison rapide ainsi que des retours gratuits.</p>
      </div>
    </div>
  </section>
</div>

app/views/shared/_footer.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <title>Footer</title>
</head>
  <footer class="footer">
  	 <div class="container1">
  	 	<div class="row1">
  	 		<div class="footer-col">
  	 			<h4>THP</h4>
  	 			<ul>
  	 				<li><a href="#">Semaine 8</a></li>
  	 				<li><a href="#">Jour 2</a></li>
  	 				<li><a href="#">Ma copine m'a quitté</a></li>
  	 				<li><a href="#">Et je sais toujours pas coder</a></li>
  	 			</ul>
  	 		</div>
  	 		<div class="footer-col">
  	 			<h4>Besoin d'aide?</h4>
  	 			<ul>
  	 				<li><a href="#">FAQ</a></li>
  	 				<li><a href="#">Et si </a></li>
  	 				<li><a href="#">Tu trouves pas</a></li>
  	 				<li><a href="#">Dans la FAQ</a></li>
  	 				<li><a href="#">Demmerde-toi</a></li>
  	 			</ul>
  	 		</div>
  	 		<div class="footer-col">
  	 			<h4>Team</h4>
  	 			<ul>
  	 				<li><a href="#">Damian PIERRE-LOUIS</a></li>
  	 				<li><a href="#">Lois Kouninef</a></li>
  	 				<li><a href="#">Samuel Khalifa</a></li>
  	 				<li><a href="#">Enzo Bonnet</a></li>
  	 			</ul>
  	 		</div>
  	 		<div class="footer-col">
  	 			<h4>Follow us</h4>
  	 			<div class="social-links">
  	 				<a href="#"><i class="fab fa-facebook-f"></i></a>
  	 				<a href="#"><i class="fab fa-twitter"></i></a>
  	 				<a href="#"><i class="fab fa-instagram"></i></a>
  	 				<a href="#"><i class="fab fa-linkedin-in"></i></a>
  	 			</div>
  	 		</div>
  	 	</div>
  	 </div>
  </footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid">

  <a class="navbar-brand" href="<%= root_path %>">Picat</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Accueil</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
    </ul>
  <div class="cobutton">
    <% if user_signed_in? %>
      <span class="navbar-text nav-link">
        <%= link_to "Mon panier", cart_path(current_user.cart.id) %>
        <%= link_to "Mon compte", edit_user_registration_path %>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      </span>
    <% else %>
      <span class="navbar-text nav-link">
        <%= link_to "Sign in", new_user_session_path %>
        <%= link_to "Sign up", new_user_registration_path %>
      </span>
    <% end %>
  </div>
</div>
</nav>